plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hyper.emu'
    compileSdk 34
    
    defaultConfig {
        applicationId "com.hyper.emu"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0-Winlator-Base"
    }

    sourceSets {
        main {
            // GitHub-a deyirik ki, kodları bu qovluqlarda axtar
            java.srcDirs = ['src/main/java', 'src/main/cpp']
            res.srcDirs = ['src/main/res']
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
    }
}
